### ISSUE TITLE
[ENCHANCEMENT] [UI] - Updated user cards to match horizontal layout from design files

### ISSUE THREAD

**Issue by nathanrydel** [charleschitty/friender#2]
Need to update the card design of the /users endpoint to match design file

## Todo

- [x] Update styles file to add required color scheme changes
- [x] Make user cards horizontal for /users endpoint template
- [x] Match list design color to base design color scheme
